package net.gjerull.etherpad.client;

// Generated by GraphWalker (http://www.graphwalker.org)
import org.graphwalker.java.annotation.Edge;
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;

@Model(file = "unnamed0.graphml")
public interface Graph {

	@Vertex()
	void init();

	@Edge()
	void e_GetText();

	@Edge()
	void e_DeletePad();

	@Edge()
	void e_setup();

	@Edge()
	void e_CreatePad();

	@Vertex()
	void v_ExistePad();

	@Edge()
	void e_SetText();

	@Vertex()
	void v_NoExistePad();
}
